# fly.toml app configuration file generated for workshop-app-still-cherry-5077 on 2025-05-19T10:52:16+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'workshop-app-still-cherry-5077'
primary_region = 'arn'

[build]



[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
